"""AquaAlert AI — Agent 5 Page: Tactical Alerts & Safety Recommendations.

Implements Section 6.4:
- Real-time civil defense bulletins for municipal agencies and citizen commuters.
- Categorized by urgency with immediate operational advisories.
"""

from typing import List
import streamlit as st
from backend.contracts import GridPredictionResult
from app.components.alert_card import render_alert_cards


def render_alerts_page(
    grid_results: List[GridPredictionResult],
    selected_area: str,
) -> None:
    """Render the Alerts & Recommendations stage view."""
    st.subheader(f"⚠️ Active Flood & Inundation Advisories — {selected_area}")
    st.caption("Actionable recommendations generated by the AquaAlert Hybrid Decision Engine.")

    render_alert_cards(grid_results)
